# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.net_info_peer import NetInfoPeer  # noqa: E501
from swagger_client.rest import ApiException


class TestNetInfoPeer(unittest.TestCase):
    """NetInfoPeer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetInfoPeer(self):
        """Test NetInfoPeer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.net_info_peer.NetInfoPeer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
