# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.token_api import TokenApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self):
        self.api = TokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_get_nft_get(self):
        """Test case for api_v1_get_nft_get

        """
        pass

    def test_api_v1_get_nfts_get(self):
        """Test case for api_v1_get_nfts_get

        """
        pass

    def test_api_v1_get_token_balance_get(self):
        """Test case for api_v1_get_token_balance_get

        """
        pass

    def test_api_v1_get_token_data_get(self):
        """Test case for api_v1_get_token_data_get

        """
        pass

    def test_api_v1_get_token_get(self):
        """Test case for api_v1_get_token_get

        """
        pass

    def test_api_v1_get_tokens_get(self):
        """Test case for api_v1_get_tokens_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
