# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sale_api import SaleApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSaleApi(unittest.TestCase):
    """SaleApi unit test stubs"""

    def setUp(self):
        self.api = SaleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_get_latest_sale_hash_get(self):
        """Test case for api_v1_get_latest_sale_hash_get

        """
        pass

    def test_api_v1_get_sale_get(self):
        """Test case for api_v1_get_sale_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
