# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.validator_settings import ValidatorSettings  # noqa: E501
from swagger_client.rest import ApiException


class TestValidatorSettings(unittest.TestCase):
    """ValidatorSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidatorSettings(self):
        """Test ValidatorSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.validator_settings.ValidatorSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
