# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transaction_api import TransactionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionApi(unittest.TestCase):
    """TransactionApi unit test stubs"""

    def setUp(self):
        self.api = TransactionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_get_address_transaction_count_get(self):
        """Test case for api_v1_get_address_transaction_count_get

        """
        pass

    def test_api_v1_get_address_transactions_get(self):
        """Test case for api_v1_get_address_transactions_get

        """
        pass

    def test_api_v1_get_transaction_by_block_hash_and_index_get(self):
        """Test case for api_v1_get_transaction_by_block_hash_and_index_get

        """
        pass

    def test_api_v1_get_transaction_get(self):
        """Test case for api_v1_get_transaction_get

        """
        pass

    def test_api_v1_invoke_raw_script_get(self):
        """Test case for api_v1_invoke_raw_script_get

        """
        pass

    def test_api_v1_send_raw_transaction_get(self):
        """Test case for api_v1_send_raw_transaction_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
