# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_api import AccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_get_account_get(self):
        """Test case for api_v1_get_account_get

        """
        pass

    def test_api_v1_get_accounts_get(self):
        """Test case for api_v1_get_accounts_get

        """
        pass

    def test_api_v1_get_addresses_by_symbol_get(self):
        """Test case for api_v1_get_addresses_by_symbol_get

        """
        pass

    def test_api_v1_look_up_name_get(self):
        """Test case for api_v1_look_up_name_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
