# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.contract_api import ContractApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContractApi(unittest.TestCase):
    """ContractApi unit test stubs"""

    def setUp(self):
        self.api = ContractApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_get_contract_by_address_get(self):
        """Test case for api_v1_get_contract_by_address_get

        """
        pass

    def test_api_v1_get_contract_get(self):
        """Test case for api_v1_get_contract_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
