# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.net_info_peer_connection_status import NetInfoPeerConnectionStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestNetInfoPeerConnectionStatus(unittest.TestCase):
    """NetInfoPeerConnectionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetInfoPeerConnectionStatus(self):
        """Test NetInfoPeerConnectionStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.net_info_peer_connection_status.NetInfoPeerConnectionStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
