# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.node_info import NodeInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestNodeInfo(unittest.TestCase):
    """NodeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeInfo(self):
        """Test NodeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.node_info.NodeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
