# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.net_info_peer_connection_status_monitor import NetInfoPeerConnectionStatusMonitor  # noqa: E501
from swagger_client.rest import ApiException


class TestNetInfoPeerConnectionStatusMonitor(unittest.TestCase):
    """NetInfoPeerConnectionStatusMonitor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetInfoPeerConnectionStatusMonitor(self):
        """Test NetInfoPeerConnectionStatusMonitor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.net_info_peer_connection_status_monitor.NetInfoPeerConnectionStatusMonitor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
