# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.connection_api import ConnectionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConnectionApi(unittest.TestCase):
    """ConnectionApi unit test stubs"""

    def setUp(self):
        self.api = ConnectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_abci_query_get(self):
        """Test case for api_v1_abci_query_get

        """
        pass

    def test_api_v1_get_validators_settings_get(self):
        """Test case for api_v1_get_validators_settings_get

        """
        pass

    def test_api_v1_health_get(self):
        """Test case for api_v1_health_get

        """
        pass

    def test_api_v1_net_info_get(self):
        """Test case for api_v1_net_info_get

        """
        pass

    def test_api_v1_request_block_get(self):
        """Test case for api_v1_request_block_get

        """
        pass

    def test_api_v1_status_get(self):
        """Test case for api_v1_status_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
