# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rpc_api import RpcApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRpcApi(unittest.TestCase):
    """RpcApi unit test stubs"""

    def setUp(self):
        self.api = RpcApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rpc_post(self):
        """Test case for rpc_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
