# coding: utf-8

"""
    Phantasma API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RpcResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'jsonrpc': 'str',
        'result': 'object',
        'id': 'int'
    }

    attribute_map = {
        'jsonrpc': 'jsonrpc',
        'result': 'result',
        'id': 'id'
    }

    def __init__(self, jsonrpc=None, result=None, id=None):  # noqa: E501
        """RpcResponse - a model defined in Swagger"""  # noqa: E501
        self._jsonrpc = None
        self._result = None
        self._id = None
        self.discriminator = None
        if jsonrpc is not None:
            self.jsonrpc = jsonrpc
        if result is not None:
            self.result = result
        if id is not None:
            self.id = id

    @property
    def jsonrpc(self):
        """Gets the jsonrpc of this RpcResponse.  # noqa: E501


        :return: The jsonrpc of this RpcResponse.  # noqa: E501
        :rtype: str
        """
        return self._jsonrpc

    @jsonrpc.setter
    def jsonrpc(self, jsonrpc):
        """Sets the jsonrpc of this RpcResponse.


        :param jsonrpc: The jsonrpc of this RpcResponse.  # noqa: E501
        :type: str
        """

        self._jsonrpc = jsonrpc

    @property
    def result(self):
        """Gets the result of this RpcResponse.  # noqa: E501


        :return: The result of this RpcResponse.  # noqa: E501
        :rtype: object
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this RpcResponse.


        :param result: The result of this RpcResponse.  # noqa: E501
        :type: object
        """

        self._result = result

    @property
    def id(self):
        """Gets the id of this RpcResponse.  # noqa: E501


        :return: The id of this RpcResponse.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RpcResponse.


        :param id: The id of this RpcResponse.  # noqa: E501
        :type: int
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RpcResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RpcResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
